export const hubDefinitions = {
  'mushroom-identification-safety': {
    title: 'Mushroom Identification Safety Hub',
    seoTitle: 'Mushroom Identification Safety Hub',
    description: 'A safety-first path through mushroom identification guides, poisonous warning signs, lookalikes, field documentation, and responsible next steps.',
    eyebrow: 'Identification hub',
    intro: 'Use this hub when the search intent is bigger than one species. It connects the safety rules, field methods, and lookalike comparisons that should come before any wild mushroom confidence call.',
    primary: ['identification/mushroom-identification-safety-checklist', 'identification/how-to-identify-mushrooms', 'identification/poisonous-mushroom-warning-signs', 'identification/oyster-mushroom-lookalikes', 'identification/chanterelle-vs-jack-o-lantern', 'identification/false-morel-vs-morel'],
    categories: ['identification', 'mushrooms'],
    questions: ['Can I identify this from one photo?', 'Which features matter before comparing lookalikes?', 'When should I stop and ask a local expert?'],
    safety: 'No page on this site confirms edibility. Keep unknown mushrooms out of the kitchen until a qualified local expert has examined the complete specimen in person.',
  },
  'mushroom-nutrition-evidence': {
    title: 'Mushroom Nutrition Evidence Hub',
    seoTitle: 'Mushroom Nutrition Evidence Hub',
    description: 'Compare mushroom nutrition, vitamin D, beta-glucans, gut health, heart health, immune claims, supplements, and evidence limits in one organized hub.',
    eyebrow: 'Health evidence hub',
    intro: 'This hub separates ordinary mushroom foods from extracts, supplements, and disease-related claims so readers can move from broad nutrition questions to specific evidence reviews.',
    primary: ['health/mushroom-nutrition-guide', 'health/cooked-vs-raw-mushrooms', 'health/mushrooms-vitamin-d', 'health/mushroom-beta-glucans', 'health/mushrooms-gut-health', 'health/mushrooms-heart-health', 'health/mushrooms-immune-system', 'health/mushroom-supplements-guide'],
    categories: ['health'],
    questions: ['What nutrients do mushrooms actually provide?', 'Which claims are food composition versus clinical evidence?', 'How should supplement labels be evaluated?'],
    safety: 'Health pages are educational and cannot replace diagnosis, treatment, or individualized medical guidance.',
  },
  'beginner-mushroom-growing': {
    title: 'Beginner Mushroom Growing Hub',
    seoTitle: 'Beginner Mushroom Growing Hub',
    description: 'Start growing mushrooms with guides to beginner methods, substrates, fruiting chambers, contamination, coffee grounds, harvest timing, and troubleshooting.',
    eyebrow: 'Growing hub',
    intro: 'A practical route through authenticated spawn, substrate choices, fruiting conditions, contamination decisions, and harvest timing for home growers.',
    primary: ['growing/mushroom-growing-beginners', 'growing/grow-oyster-mushrooms-home', 'growing/mushroom-substrate-guide', 'growing/build-mushroom-fruiting-chamber', 'growing/mushroom-fruiting-conditions', 'growing/grow-mushrooms-coffee-grounds', 'growing/mushroom-contamination-guide', 'growing/when-to-harvest-mushrooms'],
    categories: ['growing'],
    questions: ['Which method is most reliable for a first crop?', 'How do substrate, humidity, and fresh air connect?', 'When should a batch be discarded instead of rescued?'],
    safety: 'Use authenticated cultures and do not eat mushrooms from contaminated or unexpected growth.',
  },
  'easy-mushroom-recipes': {
    title: 'Easy Mushroom Recipes Hub',
    seoTitle: 'Easy Mushroom Recipes Hub',
    description: 'Cook cultivated mushrooms with easy recipes for sauteed mushrooms, mushroom toast, gravy, pasta, air fryer mushrooms, soup, risotto, and quick dinners.',
    eyebrow: 'Recipe hub',
    intro: 'This hub groups dependable cultivated-mushroom recipes by technique: browning, crisping, simmering, saucing, and using leftovers safely.',
    primary: ['recipes/sauteed-mushrooms-recipe', 'recipes/mushroom-toast', 'recipes/mushroom-gravy', 'recipes/air-fryer-mushrooms', 'recipes/mushroom-pasta', 'recipes/mushroom-risotto', 'recipes/creamy-mushroom-soup', 'recipes/garlic-butter-oyster-mushrooms'],
    categories: ['recipes'],
    questions: ['How do I brown mushrooms instead of steaming them?', 'Which quick recipe should I make tonight?', 'How should leftovers be cooled and reheated?'],
    safety: 'Recipes use mushrooms sold as food by reputable suppliers. A recipe cannot identify a wild mushroom.',
  },
  'oyster-mushroom-guide': {
    title: 'Oyster Mushroom Topic Hub',
    seoTitle: 'Oyster Mushroom Guides: Cooking, Growing, Lookalikes',
    description: 'Explore oyster mushroom identification context, lookalikes, home growing, fruiting conditions, straw methods, and cooking ideas in one topic hub.',
    eyebrow: 'Species topic hub',
    intro: 'Oyster mushrooms connect several high-intent topics: species background, cultivated blocks, fruiting conditions, lookalike safety, and fast recipes.',
    primary: ['mushrooms/oyster-mushroom-guide', 'identification/oyster-mushroom-lookalikes', 'growing/grow-oyster-mushrooms-home', 'growing/grow-mushrooms-straw', 'growing/build-mushroom-fruiting-chamber', 'recipes/garlic-butter-oyster-mushrooms', 'recipes/air-fryer-mushrooms'],
    categories: ['mushrooms', 'identification', 'growing', 'recipes'],
    questions: ['What should I know before eating or growing oyster mushrooms?', 'Which pages cover lookalikes versus cultivation?', 'Which recipes work best with cultivated oyster mushrooms?'],
    safety: 'Store-bought or authenticated cultivated oyster mushrooms are different from wild oyster-like specimens. Keep identification and cooking decisions separate.',
  },
} as const;

export type HubKey = keyof typeof hubDefinitions;
